build:
    environment:
        python: '2.7.7'
    dependencies:
        before:
            - sudo apt-get install -y libxml2-dev libxslt-dev python-dev
filter:
    excluded_paths:
        - 'tests/*'
        - '*/propertymappings.py'
        - '*/valueformatters.py'